DROP TABLE IF EXISTS payments;

DROP TABLE IF EXISTS tickets;

DROP TABLE IF EXISTS flights;

DROP TABLE IF EXISTS canceling_situations;

DROP TABLE IF EXISTS airplanes;

DROP TABLE IF EXISTS cities;

DROP TABLE IF EXISTS passengers;

DROP TABLE IF EXISTS users;
