DROP TABLE IF EXISTS payment;

DROP TABLE IF EXISTS ticket;

DROP TABLE IF EXISTS flight;

DROP TABLE IF EXISTS canceling_situation;

DROP TABLE IF EXISTS airplane;

DROP TABLE IF EXISTS city;

DROP TABLE IF EXISTS passenger;

DROP TABLE IF EXISTS user;
