# redis configuration
redis:
  host: localhost
  port: 6379
  password: dbpassword
  TTL: 1 * time.Minute 
# database configuration
database:  
  driver: mysql
  host: "127.0.0.1"
  port: 3306
  db: aliagha
  username: root
  password: root
  charset: "utf8mb4"
# Server configuration
server:
  address: localhost
  port: 8080
# Payment gateway configuration
payment_gateway:
  url: https://banktest.ir/api
  api_key: myapikey
  api_secret: myapisecret
# Mock API configuration
mock_api:
  url: https://mockapi.com/api
  auth_key: myauthkey
  auth_secret: myauthsecret
# Security configuration
security:
  secret_key: mysecretkey
  encryption_algorithm: AES-256  
# Jwt-based authentication configuration
jwt:
  secret_key: mysecretkey
  expires_in: 24 * time.Hour